/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package mobile.shop.GUI;

import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import mobile.shop.Dao.ManageCategoryDao;
//import static mobile.shop.DBUtil.ManageCategoryDao.cate;
import mobile.shop.bean.Categorysbean;

/**
 *
 * @author Dipak
 */
public class Manage_CategoriesGui extends javax.swing.JInternalFrame {
        public static Categorysbean cat;
       
    /**
     * Creates new form Menu1
     */
    public Manage_CategoriesGui() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui =(BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
       
       // this.setLocation(0,0);
        
      
              
    }   
        public boolean validatecat()
        {
            if(txt_cat.getText().equals(""))
            {
                jLabel8.setText("Please Enter Category");
                return false;
            }
            return true;
        }
         public boolean validatesubcat()
        {
            
            if(combocat.getSelectedIndex()== -1)
            {
                jLabel18.setText("Please Select Category");
                return false;
            }
            if(sub_cat.getText().equals(""))
            {
                //jLabel16.setText("Please Enter Sub Category");
                return false;
            }
                
           
            return true;
        }
        public void SetValues()
        {
            cat = new Categorysbean();
            cat.setCategory_Title(txt_cat.getText());
        }
        public void SetSubValues()
        {
            cat = new Categorysbean();
            cat.setCategory_Title((String)combocat.getSelectedItem());
            cat.setSub_Category_Title(sub_cat.getText());
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        Clear_btn = new com.k33ptoo.components.KButton();
        Clear_btn1 = new com.k33ptoo.components.KButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_cat = new javax.swing.JTextField();
        Clear_btn3 = new com.k33ptoo.components.KButton();
        saveCat = new com.k33ptoo.components.KButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        combocat = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        sub_cat = new javax.swing.JTextField();
        saveCat1 = new com.k33ptoo.components.KButton();
        Clear_btn2 = new com.k33ptoo.components.KButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        delcombocat2 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        delsubcat = new com.k33ptoo.components.KButton();
        jLabel15 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        delcombocat = new javax.swing.JComboBox<>();
        Clear_btn4 = new com.k33ptoo.components.KButton();
        jLabel19 = new javax.swing.JLabel();

        Clear_btn.setBackground(new java.awt.Color(16, 72, 119));
        Clear_btn.setBorder(null);
        Clear_btn.setForeground(new java.awt.Color(16, 72, 119));
        Clear_btn.setText("Clear");
        Clear_btn.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        Clear_btn.setkBackGroundColor(new java.awt.Color(16, 72, 119));
        Clear_btn.setkBorderRadius(35);
        Clear_btn.setkEndColor(new java.awt.Color(255, 255, 255));
        Clear_btn.setkHoverEndColor(new java.awt.Color(204, 204, 204));
        Clear_btn.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        Clear_btn.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        Clear_btn.setkPressedColor(new java.awt.Color(0, 204, 204));
        Clear_btn.setkSelectedColor(new java.awt.Color(16, 72, 119));
        Clear_btn.setkStartColor(new java.awt.Color(255, 0, 0));

        Clear_btn1.setBackground(new java.awt.Color(16, 72, 119));
        Clear_btn1.setBorder(null);
        Clear_btn1.setForeground(new java.awt.Color(16, 72, 119));
        Clear_btn1.setText("Clear");
        Clear_btn1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        Clear_btn1.setkBackGroundColor(new java.awt.Color(16, 72, 119));
        Clear_btn1.setkBorderRadius(35);
        Clear_btn1.setkEndColor(new java.awt.Color(255, 255, 255));
        Clear_btn1.setkHoverEndColor(new java.awt.Color(204, 204, 204));
        Clear_btn1.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        Clear_btn1.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        Clear_btn1.setkPressedColor(new java.awt.Color(0, 204, 204));
        Clear_btn1.setkSelectedColor(new java.awt.Color(16, 72, 119));
        Clear_btn1.setkStartColor(new java.awt.Color(255, 0, 0));

        jLabel10.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 255));
        jLabel10.setText("Add Categories");

        jLabel11.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 255));
        jLabel11.setText("Add Sub Categories");

        jTabbedPane2.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTabbedPane2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTabbedPane2.setFocusable(false);
        jTabbedPane2.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jTabbedPane2.setOpaque(true);
        jTabbedPane2.setVerifyInputWhenFocusTarget(false);

        jPanel3.setBackground(new java.awt.Color(0, 0, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(16, 72, 119)));
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Add New Product Category");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(423, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(423, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(131, 169, 215));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel4.setText("Add Categories");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel3.setText("Enter  Category ");

        txt_cat.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txt_cat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txt_cat.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_catFocusGained(evt);
            }
        });

        Clear_btn3.setBackground(new java.awt.Color(16, 72, 119));
        Clear_btn3.setBorder(null);
        Clear_btn3.setForeground(new java.awt.Color(16, 72, 119));
        Clear_btn3.setText("Clear");
        Clear_btn3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        Clear_btn3.setkBackGroundColor(new java.awt.Color(16, 72, 119));
        Clear_btn3.setkBorderRadius(35);
        Clear_btn3.setkEndColor(new java.awt.Color(255, 255, 255));
        Clear_btn3.setkHoverEndColor(new java.awt.Color(204, 204, 204));
        Clear_btn3.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        Clear_btn3.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        Clear_btn3.setkPressedColor(new java.awt.Color(0, 204, 204));
        Clear_btn3.setkSelectedColor(new java.awt.Color(16, 72, 119));
        Clear_btn3.setkStartColor(new java.awt.Color(255, 0, 0));
        Clear_btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Clear_btn3ActionPerformed(evt);
            }
        });

        saveCat.setBackground(new java.awt.Color(16, 72, 119));
        saveCat.setBorder(null);
        saveCat.setForeground(new java.awt.Color(16, 72, 119));
        saveCat.setText("Add");
        saveCat.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        saveCat.setkBackGroundColor(new java.awt.Color(16, 72, 119));
        saveCat.setkBorderRadius(35);
        saveCat.setkEndColor(new java.awt.Color(255, 255, 255));
        saveCat.setkHoverEndColor(new java.awt.Color(204, 204, 204));
        saveCat.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        saveCat.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        saveCat.setkPressedColor(new java.awt.Color(0, 204, 204));
        saveCat.setkSelectedColor(new java.awt.Color(16, 72, 119));
        saveCat.setkStartColor(new java.awt.Color(0, 51, 255));
        saveCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveCatActionPerformed(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(166, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(saveCat, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Clear_btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txt_cat, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(167, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel4)
                .addGap(130, 130, 130)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_cat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveCat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Clear_btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(131, 169, 215));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel6.setForeground(new java.awt.Color(255, 255, 255));

        jLabel18.setForeground(new java.awt.Color(255, 0, 0));
        jLabel18.setText("         ");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel5.setText("Add Sub Categories");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel6.setText("Select Category");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        combocat.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        combocat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        combocat.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                combocatFocusGained(evt);
            }
        });
        combocat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                combocatMouseEntered(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel7.setText("Enter Sub Category");

        sub_cat.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        sub_cat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        sub_cat.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                sub_catFocusGained(evt);
            }
        });
        sub_cat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub_catActionPerformed(evt);
            }
        });

        saveCat1.setBackground(new java.awt.Color(16, 72, 119));
        saveCat1.setBorder(null);
        saveCat1.setForeground(new java.awt.Color(16, 72, 119));
        saveCat1.setText("Add");
        saveCat1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        saveCat1.setkBackGroundColor(new java.awt.Color(16, 72, 119));
        saveCat1.setkBorderRadius(35);
        saveCat1.setkEndColor(new java.awt.Color(255, 255, 255));
        saveCat1.setkHoverEndColor(new java.awt.Color(204, 204, 204));
        saveCat1.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        saveCat1.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        saveCat1.setkPressedColor(new java.awt.Color(0, 204, 204));
        saveCat1.setkSelectedColor(new java.awt.Color(16, 72, 119));
        saveCat1.setkStartColor(new java.awt.Color(0, 51, 255));
        saveCat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveCat1ActionPerformed(evt);
            }
        });

        Clear_btn2.setBackground(new java.awt.Color(16, 72, 119));
        Clear_btn2.setBorder(null);
        Clear_btn2.setForeground(new java.awt.Color(16, 72, 119));
        Clear_btn2.setText("Clear");
        Clear_btn2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        Clear_btn2.setkBackGroundColor(new java.awt.Color(16, 72, 119));
        Clear_btn2.setkBorderRadius(35);
        Clear_btn2.setkEndColor(new java.awt.Color(255, 255, 255));
        Clear_btn2.setkHoverEndColor(new java.awt.Color(204, 204, 204));
        Clear_btn2.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        Clear_btn2.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        Clear_btn2.setkPressedColor(new java.awt.Color(0, 204, 204));
        Clear_btn2.setkSelectedColor(new java.awt.Color(16, 72, 119));
        Clear_btn2.setkStartColor(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(166, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(sub_cat, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(saveCat1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(Clear_btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(combocat, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(167, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel5)
                .addGap(116, 116, 116)
                .addComponent(jLabel6)
                .addGap(0, 0, 0)
                .addComponent(combocat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addGap(0, 0, 0)
                .addComponent(sub_cat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveCat1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Clear_btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        jTabbedPane2.addTab("Add Categories", jPanel3);

        jPanel2.setBackground(new java.awt.Color(173, 139, 252));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(16, 72, 119), 2));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel5.setBackground(new java.awt.Color(102, 102, 102));

        jLabel2.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(" Delete Product Category");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(429, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap(429, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(204, 204, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel17.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel17.setText("Select  Sub Category");

        delcombocat2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        delcombocat2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                delcombocat2FocusGained(evt);
            }
        });
        delcombocat2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delcombocat2ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel13.setText("Delete Sub Categories");

        delsubcat.setBackground(new java.awt.Color(16, 72, 119));
        delsubcat.setBorder(null);
        delsubcat.setForeground(new java.awt.Color(16, 72, 119));
        delsubcat.setText("Delete");
        delsubcat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        delsubcat.setkBackGroundColor(new java.awt.Color(16, 72, 119));
        delsubcat.setkBorderRadius(35);
        delsubcat.setkEndColor(new java.awt.Color(255, 255, 255));
        delsubcat.setkHoverEndColor(new java.awt.Color(204, 204, 204));
        delsubcat.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        delsubcat.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        delsubcat.setkPressedColor(new java.awt.Color(0, 204, 204));
        delsubcat.setkSelectedColor(new java.awt.Color(16, 72, 119));
        delsubcat.setkStartColor(new java.awt.Color(255, 0, 0));
        delsubcat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delsubcatActionPerformed(evt);
            }
        });

        jLabel15.setBackground(new java.awt.Color(255, 51, 51));
        jLabel15.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(delcombocat2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(delsubcat, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel13))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel13)
                .addGap(116, 116, 116)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(delcombocat2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(delsubcat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(204, 204, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel12.setText("Delete  Category");

        jLabel14.setBackground(new java.awt.Color(0, 0, 0));
        jLabel14.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel14.setText("Select Category");

        delcombocat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        delcombocat.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                delcombocatFocusGained(evt);
            }
        });

        Clear_btn4.setBackground(new java.awt.Color(16, 72, 119));
        Clear_btn4.setBorder(null);
        Clear_btn4.setForeground(new java.awt.Color(16, 72, 119));
        Clear_btn4.setText("Delete");
        Clear_btn4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Clear_btn4.setkBackGroundColor(new java.awt.Color(16, 72, 119));
        Clear_btn4.setkBorderRadius(35);
        Clear_btn4.setkEndColor(new java.awt.Color(255, 255, 255));
        Clear_btn4.setkHoverEndColor(new java.awt.Color(204, 204, 204));
        Clear_btn4.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        Clear_btn4.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        Clear_btn4.setkPressedColor(new java.awt.Color(0, 204, 204));
        Clear_btn4.setkSelectedColor(new java.awt.Color(16, 72, 119));
        Clear_btn4.setkStartColor(new java.awt.Color(255, 0, 0));
        Clear_btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Clear_btn4ActionPerformed(evt);
            }
        });

        jLabel19.setBackground(new java.awt.Color(255, 51, 51));
        jLabel19.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(delcombocat, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(Clear_btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel12)
                .addGap(108, 108, 108)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(delcombocat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Clear_btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(200, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jTabbedPane2.addTab(" Delete Categories", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jTabbedPane2)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        setBounds(0, 0, 1068, 592);
    }// </editor-fold>//GEN-END:initComponents

    private void saveCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveCatActionPerformed
        // TODO add your handling code here:
        SetValues();
        if(validatecat()==true)
        {
            
      
        ManageCategoryDao M = new ManageCategoryDao();
        if(M.CheckDuplicate()==(true))
        {
           JOptionPane.showMessageDialog(this,"This category Already Exist","Mmobile Shop",1);
           txt_cat.setText("");
        }else if(M.CheckDuplicate()==false)
        {
          M.insertCategory();  
          txt_cat.setText("");
          JOptionPane.showMessageDialog(this,"Category Inserted", "Mobile Shop",1);
          
        }
          }
        
    }//GEN-LAST:event_saveCatActionPerformed
     
    private void saveCat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveCat1ActionPerformed
          SetSubValues();
        if( validatesubcat()==true)
       {
           
            ManageCategoryDao m=new ManageCategoryDao();
           if(m.ChecksubCatExist()==true)
           {
               JOptionPane.showMessageDialog(this,"This category Already Exist","mobile Shop",1);
               sub_cat.setText("");
           }else if(m.ChecksubCatExist()==false)
           { 
               m.insertSubCategory();
             sub_cat.setText("");
             JOptionPane.showMessageDialog(this,"Sub Category Added","mobile Shop",1);      
           }}
        
    }//GEN-LAST:event_saveCat1ActionPerformed

    private void Clear_btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Clear_btn3ActionPerformed
        txt_cat.setText("");
         
    }//GEN-LAST:event_Clear_btn3ActionPerformed
       void getcat()
       {
            combocat.removeAllItems();
           ManageCategoryDao m=new ManageCategoryDao();
        m.getCategory();
         for(int i=0;i<m.cate.size();i++)
           {
               
               combocat.addItem(m.cate.get(i));
           }
       }
    private void combocatFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_combocatFocusGained
        getcat();
    }//GEN-LAST:event_combocatFocusGained

    
    private void combocatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_combocatMouseEntered
      
    }//GEN-LAST:event_combocatMouseEntered

    private void txt_catFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_catFocusGained
      jLabel8.setText("");
    }//GEN-LAST:event_txt_catFocusGained

    private void sub_catActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub_catActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sub_catActionPerformed

    private void sub_catFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sub_catFocusGained
       //jLabel9.setText("");
    }//GEN-LAST:event_sub_catFocusGained

    private void Clear_btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Clear_btn4ActionPerformed
       if(delcombocat.getSelectedIndex()== -1)
       {
           jLabel19.setText("Please Select Category");
       }else
       {
           int verify = JOptionPane.showConfirmDialog(this,"Are You Sure To Delete This Category","Delete",JOptionPane.YES_NO_OPTION,2);
           System.out.print(verify);
           if(verify==0)
           { 
               ManageCategoryDao m=new ManageCategoryDao();
              cat = new Categorysbean();
              cat.setCategory_Title((String)delcombocat.getSelectedItem());
              m.deletecategory();
              JOptionPane.showMessageDialog(this,"Deletion SuccessFulll");
           }else if(verify == 1)
           {
               JOptionPane.showMessageDialog(this,"Deletion cancel");
           }
           
           
           //cat.setCategory_Title((String)delcombocat.getSelectedItem());
           
       }
    }//GEN-LAST:event_Clear_btn4ActionPerformed

    private void delcombocatFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_delcombocatFocusGained
        
            delcombocat.removeAllItems();
        ManageCategoryDao m=new ManageCategoryDao();
        m.getCategory();
         for(int i=0;i<m.cate.size();i++)
           {
             delcombocat.addItem(m.cate.get(i));
           }
    }//GEN-LAST:event_delcombocatFocusGained

    private void delcombocat2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_delcombocat2FocusGained
        jLabel15.setText("");
        delcombocat2.removeAllItems();
        ManageCategoryDao m=new ManageCategoryDao();
         m.getsubCategory();
         for(int i=0;i<m.subcat.size();i++)
           {
               
                delcombocat2.addItem(m.subcat.get(i));
           }
    }//GEN-LAST:event_delcombocat2FocusGained

    private void delsubcatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delsubcatActionPerformed
                if(delcombocat2.getSelectedIndex()== -1)
       {
           jLabel15.setText("Please Select  Sub Category");
       }else
       {
           int verify = JOptionPane.showConfirmDialog(this,"Are You Sure To Delete This Category","Delele",JOptionPane.YES_NO_OPTION,2);
          
           if(verify==0)
           { 
               ManageCategoryDao m=new ManageCategoryDao();
              cat = new Categorysbean();
              cat.setSub_Category_Title((String)delcombocat2.getSelectedItem());
              m.deletesubcategory();
              JOptionPane.showMessageDialog(this,"Deletion SuccessFulll");
           }else if(verify == 1)
           {
               JOptionPane.showMessageDialog(this,"Deletion cancel");
           }
           
           
           //cat.setCategory_Title((String)delcombocat.getSelectedItem());
           
       }
    }//GEN-LAST:event_delsubcatActionPerformed

    private void delcombocat2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delcombocat2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_delcombocat2ActionPerformed

        
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton Clear_btn;
    private com.k33ptoo.components.KButton Clear_btn1;
    private com.k33ptoo.components.KButton Clear_btn2;
    private com.k33ptoo.components.KButton Clear_btn3;
    private com.k33ptoo.components.KButton Clear_btn4;
    private javax.swing.JComboBox combocat;
    private javax.swing.JComboBox<String> delcombocat;
    private javax.swing.JComboBox<String> delcombocat2;
    private com.k33ptoo.components.KButton delsubcat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private com.k33ptoo.components.KButton saveCat;
    private com.k33ptoo.components.KButton saveCat1;
    private javax.swing.JTextField sub_cat;
    private javax.swing.JTextField txt_cat;
    // End of variables declaration//GEN-END:variables
}
