/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package mobile.shop.GUI;

import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import mobile.shop.Dao.ManageCategoryDao;
import mobile.shop.Dao.ManageProductDao;
import mobile.shop.bean.Categorysbean;
import mobile.shop.bean.Productbean;

/**
 *
 * @author Dipak
 */
public class Manage_ProductsGui extends javax.swing.JInternalFrame {
            public static Productbean product;
            public static Categorysbean cat;
            public static String updateproductname;
    /**
     * Creates new form Menu1
     */
    public Manage_ProductsGui() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui =(BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        
       // this.setLocation(0,0);
        
            

    }
    public void  setValues()
    {   cat = new Categorysbean();
        product = new Productbean();
        product.setName(txtName.getText());
        product.setBrand(txtBrand.getText());
        product.setModel(txtModel.getText());
        product.setConfiguration(txtConfig.getText());
        product.setDescription(txtDesc.getText());
        product.setPrice(Float.parseFloat (txtPrice.getText()));
        product.setImage(jTextField1.getText());
        cat.setCategory_Title((String)combocat1.getSelectedItem());
        cat.setSub_Category_Title((String)combocat2.getSelectedItem());
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        combocat1 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        combocat2 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtBrand = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtModel = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDesc = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtConfig = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        Addbtn = new com.k33ptoo.components.KButton();
        jPanel5 = new javax.swing.JPanel();
        lbl_img = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        combocat5 = new javax.swing.JComboBox();
        jLabel23 = new javax.swing.JLabel();
        combocat8 = new javax.swing.JComboBox();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        combocat9 = new javax.swing.JComboBox();
        txtName4 = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        txtBrand5 = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        txtModel5 = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        txtPrice5 = new javax.swing.JTextField();
        jScrollPane9 = new javax.swing.JScrollPane();
        txtdesc5 = new javax.swing.JTextArea();
        jLabel52 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        txtConfig5 = new javax.swing.JTextArea();
        Login_btn1 = new com.k33ptoo.components.KButton();
        Clear_btn1 = new com.k33ptoo.components.KButton();
        jLabel53 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        lbl_img1 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(16, 72, 119));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 550));

        jTabbedPane2.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane2.setFocusable(false);
        jTabbedPane2.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jTabbedPane2.setInheritsPopupMenu(true);
        jTabbedPane2.setOpaque(true);

        jPanel2.setBackground(new java.awt.Color(131, 169, 215));

        combocat1.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        combocat1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        combocat1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                combocat1FocusGained(evt);
            }
        });
        combocat1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                combocat1MouseEntered(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel3.setText("Enter Product Name");

        combocat2.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        combocat2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        combocat2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                combocat2FocusGained(evt);
            }
        });
        combocat2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                combocat2MouseEntered(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel4.setText(" Sub Category");

        txtName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel6.setText(" Category");

        txtBrand.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtBrand.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txtBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBrandActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel7.setText("Enter Product Brand");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel8.setText("Enter Product Model");

        txtModel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtModel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel9.setText("Enter Price");

        txtPrice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtPrice.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        txtDesc.setColumns(20);
        txtDesc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDesc.setLineWrap(true);
        txtDesc.setRows(5);
        jScrollPane1.setViewportView(txtDesc);

        jLabel10.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel10.setText("Enter Product Description");

        txtConfig.setColumns(20);
        txtConfig.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtConfig.setLineWrap(true);
        txtConfig.setRows(5);
        jScrollPane2.setViewportView(txtConfig);

        jLabel11.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel11.setText("Enter Product Configuration");

        Addbtn.setBackground(new java.awt.Color(16, 72, 119));
        Addbtn.setBorder(null);
        Addbtn.setForeground(new java.awt.Color(16, 72, 119));
        Addbtn.setText("Add");
        Addbtn.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        Addbtn.setkBackGroundColor(new java.awt.Color(16, 72, 119));
        Addbtn.setkBorderRadius(35);
        Addbtn.setkEndColor(new java.awt.Color(255, 255, 255));
        Addbtn.setkHoverEndColor(new java.awt.Color(204, 204, 204));
        Addbtn.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        Addbtn.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        Addbtn.setkPressedColor(new java.awt.Color(0, 204, 204));
        Addbtn.setkSelectedColor(new java.awt.Color(16, 72, 119));
        Addbtn.setkStartColor(new java.awt.Color(0, 51, 255));
        Addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_img, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_img, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE))
        );

        jButton1.setText("Upload Image");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(combocat1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(txtBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(100, 100, 100)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combocat2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Addbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 257, Short.MAX_VALUE)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jButton1))
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE))
                        .addGap(70, 70, 70))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(440, 440, 440)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 0, 0)
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(combocat1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel6)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(3, 3, 3)
                                        .addComponent(combocat2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(33, 33, 33)
                                .addComponent(jLabel11)
                                .addGap(0, 0, 0)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(Addbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(42, 42, 42))))
        );

        jTabbedPane2.addTab("Add New Products", jPanel2);

        jPanel3.setBackground(new java.awt.Color(131, 169, 215));

        combocat5.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        combocat5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        combocat5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                combocat5FocusGained(evt);
            }
        });
        combocat5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                combocat5MouseEntered(evt);
            }
        });

        jLabel23.setBackground(new java.awt.Color(0, 0, 0));
        jLabel23.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel23.setText("Name");

        combocat8.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        combocat8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        combocat8.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                combocat8FocusGained(evt);
            }
        });
        combocat8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                combocat8MouseEntered(evt);
            }
        });

        jLabel35.setBackground(new java.awt.Color(0, 0, 0));
        jLabel35.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel35.setText("Select Sub Category");

        jLabel36.setBackground(new java.awt.Color(0, 0, 0));
        jLabel36.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel36.setText("Select Product");

        combocat9.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        combocat9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        combocat9.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combocat9ItemStateChanged(evt);
            }
        });
        combocat9.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                combocat9FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                combocat9FocusLost(evt);
            }
        });
        combocat9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                combocat9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                combocat9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                combocat9MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                combocat9MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                combocat9MouseReleased(evt);
            }
        });
        combocat9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combocat9ActionPerformed(evt);
            }
        });

        txtName4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtName4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel48.setBackground(new java.awt.Color(0, 0, 0));
        jLabel48.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel48.setText("Select Category");

        jLabel49.setBackground(new java.awt.Color(0, 0, 0));
        jLabel49.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel49.setText("Brand");

        txtBrand5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtBrand5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel50.setBackground(new java.awt.Color(0, 0, 0));
        jLabel50.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel50.setText("Model");

        txtModel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtModel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel51.setBackground(new java.awt.Color(0, 0, 0));
        jLabel51.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel51.setText("Price");

        txtPrice5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtPrice5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        txtdesc5.setColumns(20);
        txtdesc5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtdesc5.setLineWrap(true);
        txtdesc5.setRows(5);
        jScrollPane9.setViewportView(txtdesc5);

        jLabel52.setBackground(new java.awt.Color(0, 0, 0));
        jLabel52.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel52.setText(" Configuration");

        txtConfig5.setColumns(20);
        txtConfig5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtConfig5.setLineWrap(true);
        txtConfig5.setRows(5);
        jScrollPane10.setViewportView(txtConfig5);

        Login_btn1.setBackground(new java.awt.Color(16, 72, 119));
        Login_btn1.setBorder(null);
        Login_btn1.setForeground(new java.awt.Color(16, 72, 119));
        Login_btn1.setText("Update");
        Login_btn1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        Login_btn1.setkBackGroundColor(new java.awt.Color(16, 72, 119));
        Login_btn1.setkBorderRadius(35);
        Login_btn1.setkEndColor(new java.awt.Color(255, 255, 255));
        Login_btn1.setkHoverEndColor(new java.awt.Color(204, 204, 204));
        Login_btn1.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        Login_btn1.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        Login_btn1.setkPressedColor(new java.awt.Color(0, 204, 204));
        Login_btn1.setkSelectedColor(new java.awt.Color(16, 72, 119));
        Login_btn1.setkStartColor(new java.awt.Color(0, 51, 255));
        Login_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login_btn1ActionPerformed(evt);
            }
        });

        Clear_btn1.setBackground(new java.awt.Color(16, 72, 119));
        Clear_btn1.setBorder(null);
        Clear_btn1.setForeground(new java.awt.Color(16, 72, 119));
        Clear_btn1.setText("Delete");
        Clear_btn1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        Clear_btn1.setkBackGroundColor(new java.awt.Color(16, 72, 119));
        Clear_btn1.setkBorderRadius(35);
        Clear_btn1.setkEndColor(new java.awt.Color(255, 255, 255));
        Clear_btn1.setkHoverEndColor(new java.awt.Color(204, 204, 204));
        Clear_btn1.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        Clear_btn1.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        Clear_btn1.setkPressedColor(new java.awt.Color(0, 204, 204));
        Clear_btn1.setkSelectedColor(new java.awt.Color(16, 72, 119));
        Clear_btn1.setkStartColor(new java.awt.Color(255, 0, 0));
        Clear_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Clear_btn1ActionPerformed(evt);
            }
        });

        jLabel53.setBackground(new java.awt.Color(0, 0, 0));
        jLabel53.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel53.setText("Description");

        jTextField2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jButton2.setText("Upload Image");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(131, 169, 215));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_img1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_img1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 228, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(16, 16, 16)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(Login_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(Clear_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(combocat5, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtName4, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBrand5, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtModel5, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrice5, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(combocat8, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(combocat9, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(20, 20, 20))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(4, 4, 4)))))))
                .addGap(96, 96, 96))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(180, 180, 180))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(combocat5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel36)
                            .addGap(0, 0, 0)
                            .addComponent(combocat9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel35)
                                .addComponent(jLabel48))
                            .addGap(0, 0, 0)
                            .addComponent(combocat8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(0, 0, 0)
                        .addComponent(txtName4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel49)
                        .addGap(0, 0, 0)
                        .addComponent(txtBrand5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel50)
                                .addGap(0, 0, 0)
                                .addComponent(txtModel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(jLabel51)
                                .addGap(0, 0, 0)
                                .addComponent(txtPrice5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel53)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(70, 70, 70)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Login_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Clear_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel52)
                        .addGap(0, 0, 0)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))))
        );

        jTabbedPane2.addTab("Update And Delete Product", jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jTabbedPane2))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1065, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE)
        );

        setBounds(0, 0, 1077, 623);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String filename = f.getAbsolutePath();
        jTextField2.setText(filename);
        Image getAbsolutePath = null;
        ImageIcon icon = new ImageIcon(filename);
        Image image =  icon.getImage().getScaledInstance(lbl_img1.getWidth(), lbl_img1.getHeight(),Image.SCALE_SMOOTH);
        lbl_img1.setIcon(icon);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Clear_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Clear_btn1ActionPerformed
        updateproductname =((String)combocat9.getSelectedItem());
        ManageProductDao m = new ManageProductDao();
        m.DeleteProduct();
    }//GEN-LAST:event_Clear_btn1ActionPerformed

    private void Login_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_btn1ActionPerformed
        product = new Productbean();
         
        updateproductname =((String)combocat9.getSelectedItem());
        product.setName(txtName4.getText());
        product.setBrand(txtBrand5.getText());
        product.setModel(txtModel5.getText());
        product.setDescription(txtdesc5.getText());
        product.setConfiguration(txtConfig5.getText());
        product.setPrice(Float.parseFloat(txtPrice5.getText()) );
        product.setImage(jTextField2.getText());
        ManageProductDao m = new ManageProductDao();
        m.UpdateProduct();
         JOptionPane.showMessageDialog(this,"Product SuccessFully Updated");
    }//GEN-LAST:event_Login_btn1ActionPerformed

    private void combocat9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combocat9ActionPerformed
        product = new Productbean();
        product.setName((String)combocat9.getSelectedItem());
        ManageProductDao m = new ManageProductDao();
        m.ShowProduct();
        txtName4.setText(product.getName());
        txtBrand5.setText(product.getBrand());
        txtModel5.setText(product.getModel());
        txtPrice5.setText(Float.toString(product.getPrice()));
        txtConfig5.setText(product.getConfiguration());
        jTextField2.setText(product.getImage());
        txtdesc5.setText(product.getDescription());
        

        Image getAbsolutePath = null;
        ImageIcon icon = new ImageIcon(product.getImage());
        Image image =  icon.getImage().getScaledInstance(lbl_img1.getWidth(), lbl_img.getHeight(),Image.SCALE_SMOOTH);
        lbl_img1.setIcon(icon);
    }//GEN-LAST:event_combocat9ActionPerformed

    private void combocat9MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_combocat9MouseReleased

    }//GEN-LAST:event_combocat9MouseReleased

    private void combocat9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_combocat9MousePressed

        // TODO add your handling code here:
    }//GEN-LAST:event_combocat9MousePressed

    private void combocat9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_combocat9MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_combocat9MouseExited

    private void combocat9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_combocat9MouseEntered

    }//GEN-LAST:event_combocat9MouseEntered

    private void combocat9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_combocat9MouseClicked

    }//GEN-LAST:event_combocat9MouseClicked

    private void combocat9FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_combocat9FocusLost

    }//GEN-LAST:event_combocat9FocusLost

    private void combocat9FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_combocat9FocusGained
        combocat9.removeAllItems();
        cat.setSub_Category_Title((String)combocat8.getSelectedItem());
        ManageProductDao m=new  ManageProductDao();
        ManageProductDao.products.clear();
        m.getproductnames();
        for(int i=0;i<ManageProductDao.products.size();i++)
        {

            combocat9.addItem(ManageProductDao.products.get(i));
        }
    }//GEN-LAST:event_combocat9FocusGained

    private void combocat9ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combocat9ItemStateChanged

    }//GEN-LAST:event_combocat9ItemStateChanged

    private void combocat8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_combocat8MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_combocat8MouseEntered

    private void combocat8FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_combocat8FocusGained
        setval1();
        combocat8.removeAllItems();
        ManageProductDao m=new  ManageProductDao();
        ManageProductDao.sub.clear();
        m.getSpecificSubcat();
        for(int i=0;i<ManageProductDao.sub.size();i++)
        {

            combocat8.addItem(ManageProductDao.sub.get(i));
        }

    }//GEN-LAST:event_combocat8FocusGained

    private void combocat5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_combocat5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_combocat5MouseEntered

    private void combocat5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_combocat5FocusGained
        ManageCategoryDao m=new ManageCategoryDao();
        combocat5.removeAllItems();
        m.getCategory();

        for(int i=0;i<m.cate.size();i++)
        {

            combocat5.addItem(m.cate.get(i));
        }
    }//GEN-LAST:event_combocat5FocusGained

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String filename = f.getAbsolutePath();
        jTextField1.setText(filename);
        Image getAbsolutePath = null;
        ImageIcon icon = new ImageIcon(filename);
        Image image =  icon.getImage().getScaledInstance(lbl_img.getWidth(), lbl_img.getHeight(),Image.SCALE_SMOOTH);
        lbl_img.setIcon(icon);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void AddbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddbtnActionPerformed
        setValues();
        ManageProductDao  m = new ManageProductDao();
        m.insert_Product();
        JOptionPane.showMessageDialog(this,"Product SuccessFully Added");

    }//GEN-LAST:event_AddbtnActionPerformed

    private void txtBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBrandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBrandActionPerformed

    private void combocat2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_combocat2MouseEntered

    }//GEN-LAST:event_combocat2MouseEntered

    private void combocat2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_combocat2FocusGained
        // TODO add your handling code here:

        combocat2.removeAllItems();
        setval();
        ManageProductDao m=new  ManageProductDao();
        ManageProductDao.sub.clear();
        m.getSpecificSubcat();
        for(int i=0;i<ManageProductDao.sub.size();i++)
        {

            combocat2.addItem(ManageProductDao.sub.get(i));
        }
    }//GEN-LAST:event_combocat2FocusGained

    private void combocat1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_combocat1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_combocat1MouseEntered

    private void combocat1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_combocat1FocusGained

        combocat2.removeAllItems();
        combocat1.removeAllItems();
        ManageCategoryDao m=new ManageCategoryDao();
        m.getCategory();
        for(int i=0;i<m.cate.size();i++)
        {

            combocat1.addItem(m.cate.get(i));
        }
    }//GEN-LAST:event_combocat1FocusGained
   public void setval()
   {
      cat = new Categorysbean();
      cat.setCategory_Title((String)combocat1.getSelectedItem());
   }
                
                   public void setval1()
   {
      cat = new Categorysbean();
      cat.setCategory_Title((String)combocat5.getSelectedItem());
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton Addbtn;
    private com.k33ptoo.components.KButton Clear_btn1;
    private com.k33ptoo.components.KButton Login_btn1;
    private javax.swing.JComboBox combocat1;
    private javax.swing.JComboBox combocat2;
    private javax.swing.JComboBox combocat5;
    private javax.swing.JComboBox combocat8;
    private javax.swing.JComboBox combocat9;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lbl_img;
    private javax.swing.JLabel lbl_img1;
    private javax.swing.JTextField txtBrand;
    private javax.swing.JTextField txtBrand5;
    private javax.swing.JTextArea txtConfig;
    private javax.swing.JTextArea txtConfig5;
    private javax.swing.JTextArea txtDesc;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtModel5;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtName4;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtPrice5;
    private javax.swing.JTextArea txtdesc5;
    // End of variables declaration//GEN-END:variables
}
