/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mobile.shop.GUI;

import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import mobile.shop.Dao.CustomerDao;
import mobile.shop.Dao.ManageStockDao;

/**
 *
 * @author Dipak
 */
public class Manage_CustomersGui extends javax.swing.JInternalFrame {
   public static int cust_id;
    /**
     * Creates new form Menu1
     */
    public Manage_CustomersGui() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        showTable();

        // this.setLocation(0,0);
    }

    public void showTable() {
        DefaultTableModel Df = (DefaultTableModel) cust.getModel();
        Df.setRowCount(0);
       new CustomerDao().getcust();
          
        for (int j = 0; j < CustomerDao.id.size() && j < CustomerDao.coloumncount; j++) {
            // for(int i=1;i< ManageStockDao.coloumncount;i++){
            Vector v = new Vector();
            
            v.add(CustomerDao.id.get(j));
            v.add(CustomerDao.Name.get(j));
            v.add(CustomerDao.Email.get(j));
            v.add(CustomerDao.gender.get(j));
            v.add(CustomerDao.Birthdate.get(j));
            v.add(CustomerDao.Address.get(j));
            v.add(CustomerDao.Aadhar.get(j));
            v.add(CustomerDao.registerdate.get(j));
            
            

            //}
            Df.addRow(v);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")


    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cust = new javax.swing.JTable();
        rmv = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(131, 169, 215));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 550));

        cust.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cust.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Name", "Email", "Gender", "BirthDate", "Address", "Aaddhar No", "Registration Date"
            }
        ));
        jScrollPane1.setViewportView(cust);

        rmv.setBackground(new java.awt.Color(255, 153, 153));
        rmv.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        rmv.setText("Remove Customer");
        rmv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rmvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(342, 342, 342)
                .addComponent(rmv, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 401, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(95, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(rmv, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 915, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
        );

        setBounds(0, 0, 927, 510);
    }// </editor-fold>//GEN-END:initComponents

    private void rmvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rmvActionPerformed
     int t =  JOptionPane.showConfirmDialog(this,"Are you Sure to Remove Customer","Remove Customer",JOptionPane.YES_NO_OPTION,2);
        if(t==JOptionPane.YES_OPTION)
        {
        DefaultTableModel Df = (DefaultTableModel) cust.getModel();
       cust_id =(Integer.parseInt(Df.getValueAt(cust.getSelectedRow(),0).toString()));
       new CustomerDao().DeleteCust();
       JOptionPane.showMessageDialog(this,"Customer Removed");
         showTable();
        }else
        JOptionPane.showMessageDialog(this,"Canceled");
    }//GEN-LAST:event_rmvActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable cust;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton rmv;
    // End of variables declaration//GEN-END:variables
}
